//select * from caminhao.post; selecionar tudo 

practice/ caminhao.post
create schema caminhao;

CREATE TABLE caminhao.post(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apelido text NOT NULL,
	placa text NOT NULL,
	ano INT NOT NULL,
	cor text NOT NULL,
	rendimento text NOT NULL
)

insert INTO caminhao.post(apelido,placa,ano,cor,rendimento) values ('Cerejinha','HAB1235', 2003, 'Vermelho', 8);

insert INTO localidades.post(nome, distancia) values ('Conceição do Mato Dentro (MG)', 428);

CREATE TABLE IF NOT EXISTS public.localidades
(
    id_localidades integer NOT NULL,
    nome_localidades character varying(50) COLLATE pg_catalog."default" NOT NULL,
    distancia_localidades numeric NOT NULL,
    CONSTRAINT localidades_pkey PRIMARY KEY (id_localidades),
    CONSTRAINT localidades_distancia_localidades_check CHECK (distancia_localidades > 0::numeric)
)

CREATE TABLE IF NOT EXISTS public.viagens
(
    id_viagens integer NOT NULL,
    id_caminhao integer NOT NULL,
    id_localidade integer NOT NULL,
    id_data character varying(8) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT viagens_pkey PRIMARY KEY (id_viagens),
    CONSTRAINT viagens_id_caminhao_fkey FOREIGN KEY (id_caminhao)
        REFERENCES public.caminhao (id_caminhao) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT viagens_id_localidade_fkey FOREIGN KEY (id_localidade)
        REFERENCES public.localidades (id_localidades) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


Create schema camnhao.viagens

CREATE TABLE viagens.post(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_apelido text NOT NULL references caminhao (id),
	id_localidades text NOT NULL references localidades (id)	
);


select * from caminhao.post where id = 2